### ISSUE TITLE
ERROR - Signage matching query does not exist

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1406]
Received this email error : 

[Geotrek] ERROR (EXTERNAL IP): Internal Server Error: /api/intervention/interventions.json

Traceback (most recent call last):

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/decorators.py", line 60, in _wrapped_view
    return decorated(self, request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(_args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, _args2, *_kwargs2)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/decorators.py", line 58, in decorated
    return view_func(self, request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/views/generic.py", line 69, in dispatch
    return super(MapEntityList, self).dispatch(request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/decorators.py", line 60, in _wrapped_view
    return decorated(self, request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(_args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/utils/decorators.py", line 25, in bound_func
    return func(self, _args2, *_kwargs2)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/decorators.py", line 58, in decorated
    return view_func(self, request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/views/base.py", line 163, in dispatch
    return super(BaseListView, self).dispatch(_args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/views/generic/base.py", line 87, in dispatch
    return handler(request, _args, *_kwargs)

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/views/generic/list.py", line 152, in get
    context = self.get_context_data()

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/views/api.py", line 70, in get_context_data
    model=self.get_model())

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/serializers/datatables.py", line 34, in serialize
    row = [attr_getters[field](obj, field) for field in columns]

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/mapentity-1.15.0-py2.7.egg/mapentity/serializers/datatables.py", line 16, in <lambda>
    attr_getters[field] = lambda obj, field: getattr(obj, field + '_display')

  File "/home/sentiers/Geotrek-0.32.2/geotrek/maintenance/models.py", line 156, in infrastructure_display
    self.infrastructure)

  File "/home/sentiers/Geotrek-0.32.2/geotrek/maintenance/models.py", line 140, in infrastructure
    return self.signages[0]

  File "/home/sentiers/Geotrek-0.32.2/geotrek/maintenance/models.py", line 196, in signages
    return [Signage.objects.existing().get(pk=self.topology.pk)]

  File "/home/sentiers/Geotrek-0.32.2/lib/eggs/Django-1.6.5-py2.7.egg/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)

DoesNotExist: Signage matching query does not exist.

<WSGIRequest
path:/api/intervention/interventions.json,
GET:<QueryDict: {u'status': [u''], u'city': [u''], u'physical_type': [u''], u'district': [u''], u'stake': [u''], u'signage': [u''], u'project': [u''], u'trail': [u''], u'land_type': [u''], u'bbox': [u'POLYGON((5.832366943359374 44.405335171450915,5.832366943359374 45.21397099441471,6.711273193359375 45.21397099441471,6.711273193359375 44.405335171450915,5.832366943359374 44.405335171450915))'], u'subcontracting': [u'1'], u'year': [u'-1'], u'work': [u''], u'type': [u''], u'competence': [u''], u'structure': [u''], u'_': [u'1426081320324']}>,
POST:<QueryDict: {}>,
COOKIES:{'csrftoken': 'vYg2rhJaBVoiCtS4zoupqU5ZNatmGqIF',
 'sessionid': 'xg8pmkzvvg75butajsek54phnd9tb3e7'},
META:{u'CSRF_COOKIE': u'vYg2rhJaBVoiCtS4zoupqU5ZNatmGqIF',
 'HTTP_ACCEPT': 'application/json, text/javascript, _/_; q=0.01',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'csrftoken=vYg2rhJaBVoiCtS4zoupqU5ZNatmGqIF; sessionid=xg8pmkzvvg75butajsek54phnd9tb3e7',
 'HTTP_HOST': 'geotrekdemo.ecrins-parcnational.fr',
 'HTTP_REFERER': 'http://geotrekdemo.ecrins-parcnational.fr/intervention/list/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0',
 'HTTP_X_FORWARDED_FOR': '212.234.114.244',
 'HTTP_X_FORWARDED_HOST': 'geotrekdemo.ecrins-parcnational.fr',
 'HTTP_X_FORWARDED_SERVER': 'geotrekdemo.ecrins-parcnational.fr',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'PATH_INFO': u'/api/intervention/interventions.json',
 'QUERY_STRING': 'structure=&status=&type=&stake=&subcontracting=1&project=&year=-1&bbox=POLYGON((5.832366943359374+44.405335171450915%2C5.832366943359374+45.21397099441471%2C6.711273193359375+45.21397099441471%2C6.711273193359375+44.405335171450915%2C5.832366943359374+44.405335171450915))&trail=&city=&district=&physical_type=&land_type=&competence=&signage=&work=&_=1426081320324',
 'RAW_URI': '/api/intervention/interventions.json?structure=&status=&type=&stake=&subcontracting=1&project=&year=-1&bbox=POLYGON((5.832366943359374+44.405335171450915%2C5.832366943359374+45.21397099441471%2C6.711273193359375+45.21397099441471%2C6.711273193359375+44.405335171450915%2C5.832366943359374+44.405335171450915))&trail=&city=&district=&physical_type=&land_type=&competence=&signage=&work=&_=1426081320324',
 'REMOTE_ADDR': '212.234.114.244',
 'REMOTE_PORT': '80',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'geotrekdemo.ecrins-parcnational.fr',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/0.17.4',
 'gunicorn.socket': <socket._socketobject object at 0x51538a0>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fad0a372270>,
 'wsgi.file_wrapper': <class gunicorn.http.wsgi.FileWrapper at 0x3249ef0>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x50a0550>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by gutard** [comment]
Maybe there is an intervention on a signage that is deleted.

**Comment by camillemonchicourt** [comment]
Cette erreur se produit quand on essaie d'afficher la liste des interventions dans GEOTREK. 
La liste ne se charge pas. 
http://geotrekdemo.ecrins-parcnational.fr/signage/list/

Pourtant, dans la BDD, aucune SIGNALETIQUE n'est à SUPPRIME = TRUE

Et si l'on recherche les interventions sur de la signalétique qui n'ont pas de correspondance dans la table des aménagements, il retourne 0 résultats : 

```
SELECT i.id, i.topology_id, i.nom , e.supprime FROM m_t_intervention i
JOIN e_t_evenement e ON i.topology_id = e.id
WHERE e.kind = 'SIGNAGE'
AND i.topology_id NOT IN (select a.evenement FROM a_t_amenagement a)
```

Donc à priori, il n'y a pas d'interventions sur une signalétique qui a été supprimé (en dur dans `a_t_amenagement` ou passé à `supprime = true`).

La requête qui correspond à la liste des interventions renvoie 131 éléments : 

```
SELECT i.nom, i.date, b.type, e.kind, s.status, j.enjeu FROM m_t_intervention i
JOIN e_t_evenement e ON e.id = i.topology_id
LEFT JOIN m_b_intervention b ON b.id = i.type
JOIN m_b_suivi s ON s.id = i.status
LEFT JOIN l_b_enjeu j ON j.id = i.enjeu
WHERE e.supprime = 'FALSE'
```

C'est peut-être du à des mélanges dans les tables car celle des INTERVENTIONS n'est pas construite comme les autres et contient pas mal de doublons avec celle des EVÈNEMENTS (geom_3D, supprime, id des evenements) : https://github.com/makinacorpus/Geotrek/issues/1285

Une piste @leplatrem  ?

**Comment by camillemonchicourt** [comment]
I updated our DEV server (http://geotrekdemo.ecrins-parcnational.fr/) but still the same problem so the INTERVENTIONS list don't load.

**Comment by camillemonchicourt** [comment]
Outdated.
