### ISSUE TITLE
Erreur export pdf G.Admin 2.15.1

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#1670]
Je viens de me rendre compte qu'il n'est plus possible d'exporter une fiche objet en pdf.
J'ai l'erreur suivante : Forbidden '[Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'
Le serveur n'est pourtant pas configuré en https.
D'autres personnes qui ont ce problème sur la 2.15.1 ? Un lien avec l'ajout du ssl dans les settings (je n'arrive d’ailleurs toujours pas à faire marcher mon email settings) ?

**Comment by camillemonchicourt** [comment]
Problème toujours existant ?

**Comment by thomaspnrhj** [comment]
j'ai toujours le problème avec l'erreur suivante : 

Internal Server Error: /document/signage-199614.odt Traceback (most recent call last):
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/views/generic/base.py", line 65, in view
    self = cls(**initkwargs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/mapentity-3.1.4-py2.7.egg/mapentity/views/generic.py", line 237, in __init__
    self.template_name = smart_get_template(self.model, suffix)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/mapentity-3.1.4-py2.7.egg/mapentity/helpers.py", line 335, in smart_get_template
    get_template(template_name)  # Will raise if not exist
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/cached.py", line 62, in load_template
    template, origin = self.find_template(template_name, template_dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/cached.py", line 41, in find_template
    template, display_name = loader(name, dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/base.py", line 17, in load_template
    template_name, template_dirs)
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/Django-1.8.18-py2.7.egg/django/template/loaders/filesystem.py", line 38, in load_template_source
    return fp.read(), filepath
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa5 in position 10: invalid start byte

+ 

Request on http://127.0.0.1:6543/?url=http%3A//randoadmin.parc-haut-jura.fr/document/signage-199614.odt&to=application/pdf failed (status=500) Traceback (most recent call last):
  File "/home/adminsig/Geotrek-admin-2.15.1/lib/eggs/mapentity-3.1.4-py2.7.egg/mapentity/helpers.py", line 151, in download_to_stream
    assert source.status_code == 200, status_error
AssertionError: Request on http://127.0.0.1:6543/?url=http%3A//randoadmin.parc-haut-jura.fr/document/signage-199614.odt&to=application/pdf failed (status=500)
Request repr(): unavailable

Mais je sais pas si c'est un problème lié à mon instance ou si c'est un bug de version?

**Comment by gutard** [comment]
Je ne sais pas d'où vient le problème initial avec `Forbidden '[Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol'`

Par contre, le 2ème problème `UnicodeDecodeError: 'utf8' codec can't decode byte 0xa5 in position 10: invalid start byte` est corrigé dans la version 2.16.1
