### ISSUE TITLE
Synchro touristic content / Failing on generating geojson

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1763]
On a Geotrek-admin 2.19.1, we imported some APIDAE touristic contents. It worked well. They dont have type, they are all in "Accomodations" category. 

The generation of ``touristiccontents.geojson`` is failing with an error on content (``must be string or read-only buffer, not tuple``) : 

```
api/fr/touristiccontents.geojson  ... failed (must be string or read-only buffer, not tuple)
```

At the end of the synchronisation, we can see that it fails on one of the touristic content but after checking it we cant find what is the problem with it : 

```
meta/fr/contenu-touristique/gite-champagnat/index.html ... failed (must be string or read-only buffer, not tuple)
api/fr/touristiccontents/42/gite-champagnat.pdf generated
Traceback (most recent call last):
  File "/home/geotrek/Geotrek/bin/django", line 126, in <module>
    sys.exit(djangorecipe.binscripts.manage('geotrek.settings.custom'))
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/djangorecipe-2.2.1-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Django-1.11.11-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Django-1.11.11-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Django-1.11.11-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Django-1.11.11-py2.7.egg/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/geotrek/Geotrek-2.19.1/geotrek/trekking/management/commands/sync_rando.py", line 764, in handle
    self.sync()
  File "/home/geotrek/Geotrek-2.19.1/geotrek/trekking/management/commands/sync_rando.py", line 688, in sync
    self.sync_trekking(lang)
  File "/home/geotrek/Geotrek-2.19.1/geotrek/trekking/management/commands/sync_rando.py", line 469, in sync_trekking
    self.sync_tourism(lang)
  File "/home/geotrek/Geotrek-2.19.1/geotrek/trekking/management/commands/sync_rando.py", line 612, in sync_tourism
    self.sync_content(lang, content)
  File "/home/geotrek/Geotrek-2.19.1/geotrek/trekking/management/commands/sync_rando.py", line 540, in sync_content
    for picture, resized in content.resized_pictures:
  File "/home/geotrek/Geotrek-2.19.1/geotrek/common/mixins.py", line 114, in resized_pictures
    thdetail = thumbnailer.get_thumbnail(aliases.get('medium'))
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/easy_thumbnails-2.5-py2.7.egg/easy_thumbnails/files.py", line 517, in get_thumbnail
    silent_template_exception=silent_template_exception)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/easy_thumbnails-2.5-py2.7.egg/easy_thumbnails/files.py", line 404, in generate_thumbnail
    subsampling=subsampling)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/easy_thumbnails-2.5-py2.7.egg/easy_thumbnails/engine.py", line 75, in save_image
    image.save(destination, format=format, **options)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Pillow-3.0.0-py2.7-linux-x86_64.egg/PIL/Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "/home/geotrek/Geotrek-2.19.1/lib/eggs/Pillow-3.0.0-py2.7-linux-x86_64.egg/PIL/PngImagePlugin.py", line 757, in _save
    data = name + b"\0\0" + zlib.compress(im.info["icc_profile"])
TypeError: must be string or read-only buffer, not tuple
sync data to web portal
sending incremental file list
```

Any idea if the problem can be due to content and what could be the content problem ?

**Comment by gutard** [comment]
It is related to one of the attached pictures of the touristic content #42 (gite champagnat). I need an access to your instance to be able to debug.

**Comment by camillemonchicourt** [comment]
It seems that it is due to the fact that they removed some touristic content in the database but it doesn't removed their images in the relation tables (no integrity rules) so it certainly is why it created some errors.

**Comment by gutard** [comment]
I don't think so.

**Comment by camillemonchicourt** [comment]
We don't use `sync_rando` anymore since Geotrek-rando V3.
Not relevant anymore.
