### ISSUE TITLE
Erreur de synchronisation de signalétique

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#1913]
Lorsque je tente de synchroniser manuellement Geotrek  en ajoutant le paramètre dans la commande -g une erreur apparaît : 

Traceback (most recent call last):
  File "/home/admin66pm/Geotrek-admin-2.24.2/bin/django", line 127, in <module>
    sys.exit(djangorecipe.binscripts.manage('geotrek.settings.custom'))
  File "/home/admin66pm/Geotrek-admin-2.24.2/lib/eggs/djangorecipe-2.2.1-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/home/admin66pm/Geotrek-admin-2.24.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/admin66pm/Geotrek-admin-2.24.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/admin66pm/Geotrek-admin-2.24.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/admin66pm/Geotrek-admin-2.24.2/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/admin66pm/Geotrek-admin-2.24.2/geotrek/trekking/management/commands/sync_rando.py", line 814, in handle
    self.sync()
  File "/home/admin66pm/Geotrek-admin-2.24.2/geotrek/trekking/management/commands/sync_rando.py", line 736, in sync
    self.sync_trekking(lang)
  File "/home/admin66pm/Geotrek-admin-2.24.2/geotrek/trekking/management/commands/sync_rando.py", line 476, in sync_trekking
    self.sync_static_file(lang, 'infrastructure/picto-signage.png')
  File "/home/admin66pm/Geotrek-admin-2.24.2/geotrek/trekking/management/commands/sync_rando.py", line 361, in sync_static_file
    self.sync_file(lang, name, settings.STATIC_ROOT, settings.STATIC_URL)
  File "/home/admin66pm/Geotrek-admin-2.24.2/geotrek/trekking/management/commands/sync_rando.py", line 354, in sync_file
    os.link(src, dst)
OSError: [Errno 2] No such file or directory

Je suis sur Geotrek-Admin 2.24.2
Mon syn_rando est en pj
[sync_rando.txt](https://github.com/GeotrekCE/Geotrek-admin/files/3039228/sync_rando.txt)

**Comment by gutard** [comment]
A priori fixé dans la version https://github.com/GeotrekCE/Geotrek-admin/releases/tag/2.26.0 (Fix signage type pictograms)
