### ISSUE TITLE
Language issue after 2.26.5 update

### ISSUE THREAD

**Issue by geofffl** [GeotrekCE/Geotrek-admin#1937]
Hi all,

After having upgraded to 2.26.5, language is messed up. The gui is now a mix of English end French, with no possibility of modification. The settings are still OK, with French as default.

![lang_1](https://user-images.githubusercontent.com/35685608/56947264-e074e100-6b2c-11e9-96a4-a25ed906f0d0.JPG)
![lang_2](https://user-images.githubusercontent.com/35685608/56947265-e074e100-6b2c-11e9-9e79-d21fff0b3489.JPG)

**Comment by camillemonchicourt** [comment]
Bizarre, on n'a pas rencontré ce problème.

**Comment by gutard** [comment]
Le script d'installation n'est probablement pas allé jusqu'au bout. En particulier l'étape `make update` et la cible `all_compilemessages` du Makefile n'ont pas été lancées ou ont échoué. Il faut regarder le fichier install.log pour analyser le problème.

**Comment by geofffl** [comment]
Ah exact merci ! Je n'ai pas épluché le log, mais de mémoire j'avais rencontré un "could not update data".
Je vais regarder ça de plus près.

**Comment by geofffl** [comment]
Effectivement : 

> Makefile:99 : la recette pour la cible « update » a échouée
> make: *** [update] Erreur 1
> + '[' 2 -ne 0 ']'
> + exit_error 11 'Could not update data !'
> + code=11

**Comment by camillemonchicourt** [comment]
Là ça dit bien qu'il y a eu un problème mais il faudrait voir un peu plus large dans le log pour des précisions sur le problème.

**Comment by geofffl** [comment]
Bon, si je comprends bien, voici l'erreur durant la commande make : 

> django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist

Pour info, j'ai lancé 2 fois la commande install avec la même erreur.
La partie du log consacrée à "make" : 
```
`+ make update
bin/develop update -f
INFO: Queued 'django-leaflet' for update.
INFO: Queued 'django-modeltranslation' for update.
INFO: Updated 'django-leaflet' with git.
INFO: Updated 'django-modeltranslation' with git.
bin/django collectstatic --clear --noinput --verbosity=0
/home/admingeotrek/Geotrek-admin/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from $
  """)
bin/django migrate --noinput
/home/admingeotrek/Geotrek-admin/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from $
  """)
Operations to perform:
  Apply all migrations: admin, auth, authent, celery_results, cirkwi, common, contenttypes, core, easy_thumbnails, feedback, flatpages, infrastructure, land, maintenan$
Running migrations:
  Applying tourism.0004_auto_20190322_1908...Traceback (most recent call last):
  File "bin/django", line 128, in <module>
    sys.exit(djangorecipe.binscripts.manage('geotrek.settings.custom'))
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/djangorecipe-2.2.1-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/migrations/executor.py", line 115, in migrate

File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/migrations/operations/fields.py", line 221, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/schema.py", line 516, in alter_field
    return self._alter_many_to_many(model, old_field, new_field, strict)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/schema.py", line 861, in _alter_many_to_many
    new_field.remote_field.through._meta.get_field(new_field.m2m_reverse_field_name()),
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/schema.py", line 531, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/postgresql/schema.py", line 112, in _alter_field
    new_db_params, strict,
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/schema.py", line 615, in _alter_field
    self.execute(self._rename_field_sql(model._meta.db_table, old_field, new_field, new_type))
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/schema.py", line 136, in execute

 File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/admingeotrek/Geotrek-admin/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist

Makefile:99 : la recette pour la cible « update » a échouée
make: *** [update] Erreur 1
+ '[' 2 -ne 0 ']'
+ exit_error 11 'Could not update data !'
+ code=11
+ shift
+ echo_error 'Could not update data !'
+ set +x
+ echo '(More details in install.log)'
(More details in install.log)
+ exit 11
```
`
Ps : désolé si mon problème n'a rien à faire dans les "issues"

**Comment by camillemonchicourt** [comment]
Ce bug a été identifié mais normalement il était réglé dans la 2.26.4 : https://github.com/GeotrekCE/Geotrek-admin/issues/1921

**Comment by geofffl** [comment]
Mise à jour vers 2.27.1 effectuée ce matin, et toujours le même problème : could not update à la fin de l'install, et mix eng et fr dans l'interface.

**Comment by camillemonchicourt** [comment]
Il faut des logs pour savoir ce qui s'est produit.

**Comment by gutard** [comment]
Que dit `./bin/django showmigrations tourism` ? Si les migrations 1 à 3 sont cochées mais pas les 4 et 5, vous pouvez tenter de faire `./bin/django migrate --fake tourism 0004` puis de relancer `./install.sh`

**Comment by geofffl** [comment]
Salut à vous deux ! Désolé pour le délai de réponse. La commande a bien fonctionné : plus d'erreur udpate après l'install, et le problème de langue a disparu. Effectivement, les migrations 1 à 3 étaient cochées, mais pas les 4 et 5.
Merci encore !

**Comment by JeanLenormand** [comment]
Même problème lors d'une MAJ de la 2.26.0 vers la 2.29.0, le script d'install se bloque sur "Could not update data".
Dans le log, même erreur : django.db.utils.ProgrammingError: column "touristiccontenttype_id" does not exist
J'ai suivi la commande indiquée ci-dessus (./bin/django migrate --fake tourism 0004) puis relancé le script d'install qui s'est déroulé sans problème.
