### ISSUE TITLE
erreur suite à la mise à jour 2.29.5 - lié au module diving

### ISSUE THREAD

**Issue by ybuthion** [GeotrekCE/Geotrek-admin#2064]
suite à la mise à jour en 2.29.5 depuis la 2.26.3, j'ai eu des erreurs lors de ma dernière synchro.

**geoadmin@pnrvpostgis:~$ /home/geoadmin/Geotrek/bin/django sync_rando --url http://geo.pnr-vercors.fr --rando-url https://rando.parc-du-vercors.fr /home/geoadmin/data**

_/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/geoadmin/Geotrek/bin/django", line 133, in <module>
    sys.exit(djangorecipe.binscripts.manage('geotrek.settings.custom'))
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/djangorecipe-2.2.1-py2.7.egg/djangorecipe/binscripts.py", line 9, in manage
    management.execute_from_command_line(sys.argv)
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 206, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/Django-1.11.14-py2.7.egg/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geoadmin/Geotrek-admin-2.29.5/geotrek/trekking/management/commands/sync_rando.py", line 26, in <module>
    from geotrek.diving.views import DivePOIViewSet, DiveServiceViewSet
  File "/home/geoadmin/Geotrek-admin-2.29.5/geotrek/diving/views.py", line 19, in <module>
    from .filters import DiveFilterSet
  File "/home/geoadmin/Geotrek-admin-2.29.5/geotrek/diving/filters.py", line 3, in <module>
    from .models import Dive
  File "/home/geoadmin/Geotrek-admin-2.29.5/geotrek/diving/models.py", line 25, in <module>
    class Practice(PictogramMixin):
  File "/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/base.py", line 118, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class geotrek.diving.models.Practice doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
geoadmin@pnrvpostgis:~$ vim /home/geoadmin/Geotrek/geotrek/settings/custom.py
geoadmin@pnrvpostgis:~$ /home/geoadmin/Geotrek/bin/django sync_rando --url http://geo.pnr-vercors.fr --rando-url https://rando.parc-du-vercors.fr /home/geoadmin/data
/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/home/geoadmin/Geotrek-admin-2.29.5/lib/eggs/html5lib-0.999999999-py2.7.egg/html5lib/_ihatexml.py:265: DataLossWarning: Coercing non-XML name
  warnings.warn("Coercing non-XML name", DataLossWarning)_

on a contourné le problème avec Probesys de la manière suivante :

dans le fichier base.py, le module diving pointe sur le schéma rando, et pour contourner le pb, on a dû activer le module diving dans le custom.py :

# Enable sensitivity module
INSTALLED_APPS += ('geotrek.sensitivity', 'geotrek.diving')

Voilou, je ne sais pas si le pb est uniquement lié à nous vercors (conf particulière ou si c'est un bug).
bon, maintenant, on se retrouve dans le géotrek admin avec un nouveau module palmes et tuba, qui ne devrait pas nous servir en dehors de la plongée spéléo

si qqun a une idée pour faire plus propre

merci

@+
yann

**Comment by camillemonchicourt** [comment]
Le problème avait déjà été identifié et était en cours de correction. 
Il vient d'être intégré : https://github.com/GeotrekCE/Geotrek-admin/pull/2063
Et une version 2.29.6 est en cours de publication : https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst
Un tag 2.29.6 est déjà créé : https://github.com/GeotrekCE/Geotrek-admin/releases

Moi, à ta place je n'aurai pas du tout installé le module Plongée. 
Maintenant tu vas devoir le désinstaller...

**Comment by LePetitTim** [comment]
> yann

As-tu trouvé une solution pour le desinstaller ? Ou utilises tu le module finalement ?
