### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by chanteclair12** [GeotrekCE/Geotrek-admin#2115]
Bonjour,
Après une installation sur une VM Ubuntu 18.04.3 LTS et la restauration du dump de la bse PGSQL, Geotrek Admin fonctionnait correctement.
Après 15j sans avoir travaillé dessus, je me retrouve avec l'erreur "Internal Server Error" après la saisie des identifiants.
Je suis allé voir dans tous les logs mais rien nulle part.
La seule chose que je trouve est dans l'onglet "Console" du mode debug de Firefox : 
`L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert.`
Est-ce un problème uniquement dû à l'URL (seulement en interne pour le moment) qui est en http et non en https ? Faut-il déclarer le protocole https quelque part dans un fichier ?
Merci de vos retours.
Cordialement.

**Comment by gutard** [comment]
En cas de "Internal Server Error" (code d'erreur 500), les détails du problème se trouvent dans le fichier de log `/var/log/supervisor/geotrek.log`. Sans voir ce fichier, il nous est impossible d'en dire plus ici. 

L'erreur dans la console de firefox n'est pas gênante. Et a priori, rien à voir avec HTTPS.

**Comment by chanteclair12** [comment]
Bonjour et merci pour ce retour.
Voici le contenu du fichier en question :

`
ERROR 2019-12-17 10:24:09,455 django.request Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/views.py", line 54, in inner
    return func(*args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/views.py", line 150, in login
    )(request)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/views.py", line 90, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/views/generic/edit.py", line 182, in post
    if form.is_valid():
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/forms/forms.py", line 385, in full_clean
    self._clean_form()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/forms/forms.py", line 412, in _clean_form
    cleaned_data = self.clean()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/forms.py", line 187, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/backends.py", line 18, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/contrib/auth/base_user.py", line 48, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/models/sql/compiler.py", line 887, in execute_sql
    cursor = self.connection.cursor()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/Django-1.11.14-py2.7.egg/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/admxxxxxx/Geotrek-admin-2.29.15/lib/eggs/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

`

**Comment by gutard** [comment]
Le serveur postgresql n'est pas démarré.

**Comment by chanteclair12** [comment]
Il me semblait que la fin du message le concernait.
La question est désormais pourquoi est-il arrêté alors que personne n'a utilisé l'application ? Est-ce un comportement normal ? Et enfin comme le redémarrer ?
Merci.

**Comment by chanteclair12** [comment]
Je viens de tenter ceci : 
`/etc/init.d/postgresql restart
[ ok ] Restarting postgresql (via systemctl): postgresql.service.`

Mais toujours la même erreur. Rien de plus consigné dans le fichier de log.

**Comment by gutard** [comment]
L'auto-hébergement de Geotrek nécessite un suivi quelques compétences en administration système Linux. Pas besoin d'être un expert mais il faut savoir se débrouiller pour se former en allant chercher de l'info sur le net.

Quelques pistes : 
* Que répond la commande `sudo service postgresql status` ?
* Et la commande `sudo netstat -tlpn` ?
* Qu'y a-t-il dans le fichier de log de postgresql `/var/log/postgresql/postgresql-*-main.log` ?

**Comment by chanteclair12** [comment]
Les compétences je tente de les acquérir en auto-formation (comme dans beaucoup de structures j'imagine) par l'installation de cette VM en test.
A la 1ère commande, la réponse est la suivante : 
`
service postgresql status
● postgresql.service - PostgreSQL RDBMS
   Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: enabled)
   Active: active (exited) since Tue 2019-12-17 09:58:05 UTC; 30min ago
  Process: 105258 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 105258 (code=exited, status=0/SUCCESS)
`

La 2nde : 
`
netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      1319/redis-server 1
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      1246/memcached
tcp        0      0 127.0.0.1:6543          0.0.0.0:*               LISTEN      104982/python
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1297/nginx: master
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1006/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1304/sshd
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      104983/python
tcp6       0      0 ::1:6379                :::*                    LISTEN      1319/redis-server 1
tcp6       0      0 :::22                   :::*                    LISTEN      1304/sshd

`
Le fichier de log PGSQL est vide.

**Comment by gutard** [comment]
Ça devient trop compliqué pour résoudre ça ici sur github. Concernant les logs il y a une rotation. Quand le fichier .log grossit il est renommé en .log.1 et le .log.1 en .log.2.gz, etc. Donc si le fichier .log est vide il faut regarder le fichier .log.1

**Comment by chanteclair12** [comment]
Le message du log1 est le suivant : 
2019-11-18 21:51:42.321 UTC [13972] geotrek@geotrekdb FATAL:  terminating connection due to unexpected postmaster exit
Concernant cet échange, le groupe Google demande l'utilisation du github. Si le github est également déclaré non adapté, où se tourner svp ?

**Comment by camillemonchicourt** [comment]
Je n'ai jamais rencontré ce problème et il n'a pas été remonté par ailleurs. 
Il semblerait que cela soit un problème lié à votre BDD PostgreSQL et non pas à Geotrek. 
Non il n'est pas normal que votre PostgreSQL soit arrêté et nous n'avons pas ce problème.

Pour aller plus loin, il faudrait soit refaire une installation propre, soit se faire aider d'un expert PostgreSQL pour voir d'où vient votre problème.

**Comment by chanteclair12** [comment]
Pour l'installation propre, c'est le cas, puisque n'étant pas parvenu à désinstaller tous les éléments d'une 1ère VM de test, celle-ci a été recréée de zéro.
J'ai ensuite suivi la procédure de migration de serveur pour réinstaller le dump de la bdd Pgsql et le jour de la réinstallation, tout cela fonctionnait parfaitement.
Si j'en crois le résultat de la requête `sudo service postgresql status` le serveur est pourtant bien actif.

**Comment by camillemonchicourt** [comment]
OK

**Comment by camillemonchicourt** [comment]
Il faut suivre la procédure d'installation officielle dans la documentation.
Le tuto est indicatif et complémentaire.

**Comment by gutard** [comment]
> 2019-11-18 21:51:42.321 UTC [13972] geotrek@geotrekdb FATAL: terminating connection due to unexpected postmaster exit

`unexpected exit` ça ressemble à un crash de postgresql. Il n'y a qu'une seul ligne ? Il n'y a rien avant ? L'horodatage date d'il y a un mois. Si il y a eu redémarrage il devrait y avoir une trace récente de ce redémarrage dans les logs.

C'est peut-être un problème d'espace disque ou RAM. Que disent :
* `df -h` ?
* `cat /proc/meminfo` ?
* le fichier de log /var/log/syslog (déclenchement du oom-killer) ?

> Concernant cet échange, le groupe Google demande l'utilisation du github. Si le github est également déclaré non adapté, où se tourner svp ?

Le logiciel Geotrek est libre et gratuit. Le support ne l'est pas forcément. C'est au bon vouloir de la communauté d'y répondre ou pas gratuitement sur GitHub. A titre perso je ne vais pas pouvoir continuer à passer beaucoup de temps à vous répondre pour un problème qui semble compliqué et pas spécialement lié à Geotrek. Et je doute que d'autres le fasse.

**Comment by chanteclair12** [comment]
df -h donne : 
`
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M  684K  795M   1% /run
/dev/sda1        49G  7.0G   42G  15% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda15      105M  3.6M  101M   4% /boot/efi
/dev/sdb1        40G   49M   38G   1% /mnt
tmpfs           796M     0  796M   0% /run/user/1000
`

cat /proc/meminfo donne : 

`
cat /proc/meminfo
MemTotal:        8144408 kB
MemFree:         5821080 kB
MemAvailable:    6288464 kB
Buffers:          109620 kB
Cached:           513208 kB
SwapCached:            0 kB
Active:          1638580 kB
Inactive:         239844 kB
Active(anon):    1255968 kB
Inactive(anon):      320 kB
Active(file):     382612 kB
Inactive(file):   239524 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               264 kB
Writeback:             0 kB
AnonPages:       1255044 kB
Mapped:           106300 kB
Shmem:               700 kB
KReclaimable:     149488 kB
Slab:             248436 kB
SReclaimable:     149488 kB
SUnreclaim:        98948 kB
KernelStack:        5088 kB
PageTables:        19952 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4072204 kB
Committed_AS:    1797732 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:            64512 kB
HardwareCorrupted:     0 kB
AnonHugePages:    466944 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      219072 kB
DirectMap2M:     5023744 kB
DirectMap1G:     5242880 kB
`

Enfin le contenu du syslog (dernières lignes) : 
`
Dec 17 11:43:25 VM-Geotrek systemd-resolved[1006]: Using degraded feature set (TCP) for DNS server 10.x.x.x.
Dec 17 11:43:45 VM-Geo systemd-resolved[1006]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 17 11:44:01 VM-Geo CRON[112423]: (postgres) CMD (/tmp/.nginx/nginx)
Dec 17 11:44:01 VM-Geo CRON[112422]: (CRON) info (No MTA installed, discarding output)
Dec 17 11:44:07 VM-Geo systemd-resolved[1006]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Dec 17 11:45:01 VM-Geo CRON[112488]: (postgres) CMD (/tmp/.nginx/nginx)
Dec 17 11:45:01 VM-Geo CRON[112487]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Dec 17 11:45:01 VM-Geo CRON[112486]: (CRON) info (No MTA installed, discarding output)
Dec 17 11:46:01 VM-Geo CRON[112555]: (postgres) CMD (/tmp/.nginx/nginx)
`

**Comment by chanteclair12** [comment]
@gutard : je comprends tout à fait la problématique du volontariat et du temps passé, je suis moi-même actif pour la communauté Qgis.

**Comment by gutard** [comment]
Il y a de la mémoire et de l'espace disque.

A titre perso, sans un contrat de support avec Makina Corpus et un accès ssh à la machine pour investiguer sur place, je ne vois pas comment aller plus loin pour vous aider. Sinon, cherchez quelqu'un compétent en administration système Linux dans votre entourage.

**Comment by chanteclair12** [comment]
Merci du temps consacré en tout cas.

**Comment by camillemonchicourt** [comment]
Vous avez un problème avec votre PostgreSQL, indépendant de Geotrek. 
Je vous conseille de réinstaller tout cela maintenant que vous maîtrisez mieux le sujet.

Ou alors vous avez un problème avec votre BDD Geotrek de fait de sa manipulation (sauvegarde, restauration).

**Comment by chanteclair12** [comment]
Bonjour,
Merci pour votre réponse.
Ce qui est bizarre, c'est que le moteur PGSQL a, d'après les logs, coupé 15 jours après l'installation/ restauration des données, sans même avoir été utilisé.

**Comment by camillemonchicourt** [comment]
Oui très bizarre, jamais rencontré ça.
Comme évoqué par @gutard, ça laissait penser à un plantage de PostgreSQL à cause d'un problème d'espace disque ou de RAM insuffisante mais ça semble pas le cas. 
Il doit y avoir des problèmes dues à différentes manipulations, raison pour laquelle je referai une installation complète. Sinon une expertise s'impose.
Bon courage !
