### ISSUE TITLE
Pg_restore 2.33.5

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2252]
Pour ma restauration de ma BBD, je lance sudo -u postgres psql -c "CREATE DATABASE geotrekdb ENCODING 'UTF8' TEMPLATE template0;" puis ensuite la commande : sudo -u psql -d geotrekdb -c "CREATE EXTENSION postgis;"

J'ai l'erreur suivante
 sudo -u psql -d geotrekdbpnrhj -c "CREATE EXTENSION postgis;"
sudo : option invalide -- 'd'
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...

-d doit permettre quelle fonctionnalité ?

**Comment by camillemonchicourt** [comment]
L'option ``-d`` permet d'indiquer sur quelle BDD tu veux exécuter la commande.

Je fais cette commande dans un autre projet, tu peux tenter comme ça en indiquant l'utilisateur ``postgres`` : 

```bash
sudo -n -u postgres -s psql -d geotrekdbpnrhj -c "CREATE EXTENSION IF NOT EXISTS postgis;"
```

**Comment by thomaspnrhj** [comment]
Ta commande fonctionne mais j'ai après un problème de droit sur BBD car quand je lance sudo dpkg-reconfigure geotrek-admin j'ai : 

CRITICAL 2020-05-15 23:12:00,289 geotrek.common.utils.postgresql Failed to install custom SQL file '/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/sql/post_20_schema.sql': permission denied for database geotrekdbpnrhj


Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InsufficientPrivilege: permission denied for database geotrekdbpnrhj


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/utils/postgresql.py", line 103, in load_sql_files
    cursor.execute(sql)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: permission denied for database geotrekdbpnrhj

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InsufficientPrivilege: permission denied for database geotrekdbpnrhj


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/migrate.py", line 28, in handle
    load_sql_files(app, 'post')
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/utils/postgresql.py", line 103, in load_sql_files
    cursor.execute(sql)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: permission denied for database geotrekdbpnrhj

permission denied for database geotrekdbpnrhjCopy static files

**Comment by camillemonchicourt** [comment]
OK le problème est la commande précédente quand tu as créé la BDD sans indiquer qui en est le propriétaire, du coup ton utilisateur de BDD (``geotrek`` certainement) n'arrive à rien exécuter dedans. 

Voila les commandes que j'ai : 

```bash
sudo -u postgres psql -c "CREATE DATABASE geotrekdb OWNER geotrek;"
sudo -u postgres psql -d geotrekdb -c "CREATE EXTENSION postgis;"
sudo -u postgres pg_restore -d geotrekdb /tmp/geotrek_dump/202004091449-database.backup
```

Si besoin, créer l'utilisateur ``geotrek``avant, mais si j'ai bien compris, il existe déjà sur ton serveur : 
```
sudo -u postgres psql -c "CREATE USER geotrek PASSWORD 'toto';"
```

**Comment by camillemonchicourt** [comment]
Il faut surement ajuster ça dans la nouvelle doc de Maintenance (Backup/Restore) : https://geotrek.readthedocs.io/en/master/maintenance.html#application-restore

On voit dans l'ancienne doc de migration de serveur les commandes avec le ``owner`` indiqué quand on créé la BDD : https://geotrek.readthedocs.io/en/2.21.1/installation.html#server-migration

**Comment by thomaspnrhj** [comment]
C'est tout bon ! merci Camille pour ton aide, c'est reparti pour un tour !

**Comment by camillemonchicourt** [comment]
OK donc il faudrait compléter/ajuster la documentation de backup/restore il me semble.

**Comment by jeromesourdin** [comment]
Bonjour,
Je profite de cette file pour vous exposer mon problème ! Je souhaite reporter mon environnement de prod sur la test, et j'ai des erreurs quand je veux recréer les extensions postgis.
`ERROR:  could not access file "$libdir/postgis-2.4": Aucun fichier ou dossier de ce type`
Auriez-vous une idée ?

Merci d'avance

**Comment by camillemonchicourt** [comment]
Salut, je ne sais pas si tu as vu les contributions à la doc sur ce sujet : https://github.com/GeotrekCE/Geotrek-admin/commit/8768e97fedf91f2cfe6ba8ea1c493c1909f382b6
On dirait que tu as un problème de version de PostGIS. En cherchant l'erreur sur internet, il y a beaucoup de discussions similaires. 
Il semble qu'il faille mettre à jour l'extension PostGIS. Voir https://github.com/postgis/docker-postgis/issues/93#issuecomment-505308463 ou encore https://stackoverflow.com/a/52591758

**Comment by jeromesourdin** [comment]
Oui, c'est ce que je pensais. J'ai regardé ma conf. J'ai migré mon serveur d'un ubuntu 16.04 vers un 18.04, et pendant cette migration, il y a eu une installation de postgres 10 mais ma base tourne toujours sur l'instance 9.5. Je pense que le problème doit venir de là. Avant, il y avait un popstgis 2.3 et depuis l'update 2.4. Par contre, je n'ai rien fais sur les bases... C'est peut être là le souci ?

**Comment by camillemonchicourt** [comment]
Je crois que normalement on peut mettre à jour la version de PostgreSQL/PostGIS sans rien avoir à faire sur les bases de données elles-mêmes.

**Comment by jeromesourdin** [comment]
Voilà ce que j'ai d'installé : 
`sudo apt list --installed |grep postgis

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

postgis/bionic,now 2.4.3+dfsg-4 amd64  [installé]
postgis-doc/bionic,bionic,now 2.4.3+dfsg-4 all  [installé, automatique]
postgresql-10-postgis-2.4/bionic,now 2.4.3+dfsg-4 amd64  [installé]
postgresql-10-postgis-2.4-scripts/bionic,bionic,now 2.4.3+dfsg-4 all  [installé, automatique]
postgresql-9.5-postgis-2.2/now 2.2.1+dfsg-2ubuntu0.1 amd64  [installé, local]
postgresql-9.5-postgis-2.3/now 2.3.2+dfsg-1~xenial0 amd64  [installé, local]
postgresql-9.5-postgis-2.4-scripts/now 2.4.2+dfsg-1~xenial0 all  [installé, local]
postgresql-9.5-postgis-scripts/now 2.4.2+dfsg-1~xenial0 all  [installé, local]`

**Comment by jeromesourdin** [comment]
Voilà ce que j'ai d'installé :

> sudo apt list --installed |grep postgis
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> postgis/bionic,now 2.4.3+dfsg-4 amd64 [installé]
> postgis-doc/bionic,bionic,now 2.4.3+dfsg-4 all [installé, automatique]
> postgresql-10-postgis-2.4/bionic,now 2.4.3+dfsg-4 amd64 [installé]
> postgresql-10-postgis-2.4-scripts/bionic,bionic,now 2.4.3+dfsg-4 all [installé, automatique]
> postgresql-9.5-postgis-2.2/now 2.2.1+dfsg-2ubuntu0.1 amd64 [installé, local]
> postgresql-9.5-postgis-2.3/now 2.3.2+dfsg-1xenial0 amd64 [installé, local]
> postgresql-9.5-postgis-2.4-scripts/now 2.4.2+dfsg-1xenial0 all [installé, local]
> postgresql-9.5-postgis-scripts/now 2.4.2+dfsg-1~xenial0 all [installé, local]

**Comment by gutard** [comment]
> Je profite de cette file pour vous exposer mon problème

Il est préférable d'ouvrir une nouvelle issue. Sinon, on mélange plein de problèmes différents et on ne peut plus différentier ce qui est résolu de ce qui ne l'est pas.

> Je crois que normalement on peut mettre à jour la version de PostgreSQL/PostGIS sans rien avoir à faire sur les bases de données elles-mêmes.

Si tu ne fais rien de plus que le `apt upgrade` la nouvelle version est installée en parallèle de l'ancienne sur le port 5433 et donc tu continues à utiliser l'ancienne version.

La procédure pour migrer la base est indiquée dans le fichier de doc /usr/share/doc/postgresql-common/README.Debian.gz au chapitre "Default clusters and upgrading". Mais il faut aussi tenir compte de postgis. Pour postgis, la doc d'upgrade est dans /usr/share/doc/postgis/README.Debian. Ça peut obliger à faire un dump/restore.

**Comment by jeromesourdin** [comment]
J'ai appliqué la mise à jour indiquée dans /usr/share/doc/postgresql-common/README.Debian.gz, c'est très rapide, et j'ai pu faire le dump et restaure ! 
Merci bcp
