### ISSUE TITLE
Questions configuration mail signalement

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2539]
Version Gtk-Admin : 2.48.1

Bonjour, 

En voulant paramétrer le mail sur la nouvelle version de Geotrek-admin je tombe sur des erreurs de syntaxe. Voici à quoi ressemblait mon ancienne config sur les version < 2.33 :

mailfrom = truc@machin.fr
mailhost = 127.0.0.1
mailuser =
mailpassword =
mailport = 25 
mailtls = False

J'ai regardé ce post : https://github.com/GeotrekCE/Geotrek-admin/issues/2393 et j'ai adapté pour la nouvelle version : 

DEFAULT_FROM_EMAIL = truc@machin.fr

SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = 127.0.0.1
EMAIL_HOST_USER =
EMAIL_HOST_PASSWORD =
EMAIL_HOST_PORT = 25
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

Puis la commande : 

Sauf que j'ai une erreur de syntaxe :

`Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/settings/__init__.py", line 1, in <module>
    from .base import *  # NoQA
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/settings/base.py", line 796, in <module>
    exec(f.read())
  File "<string>", line 85
    EMAIL_HOST = 127.0.0.1
                       ^
SyntaxError: invalid syntax`

Du coup j'ai deux questions : 

 - Est-ce que le fait de passer de ubuntu 16.04 à 18.04 ferait sauter un serveur SMTP paramétré en local ?
 - Ou bien est-on obligé de maintenant  paramétrer un serveur smtp comme google ou autre ?

**Comment by numahell** [comment]
Bonjour Michael,

En effet en python il faut toujours mettre quelque chose après le "=", ce qui n'était pas nécessaire dans le fichier .ini
Je suggère d'enlever les deux lignes

```
EMAIL_HOST_USER =
EMAIL_HOST_PASSWORD =
```

**Comment by mviadere-openig** [comment]
Bonjour numahell, merci pour ta réponse rapide :)

Alors j'avais déjà essayé et j'obtenais une autre erreur de syntaxe. J'ai tenté comme ceci : 

DEFAULT_FROM_EMAIL = 'truc@machin.fr'
# address will be set for sended emails (ex: noreply@yourdomain.net)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_HOST = '127.0.0.1'
EMAIL_HOST_PORT = 25
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False

Cela semble fonctionner. On est d'accord que lorsqu'on fait la commande `sudo geotrek test_managers_emails` si cela ne retourne rien c'est que ça a fonctionné mais ça n'envoie pas d'emails, c'est bien ça ?

**Comment by numahell** [comment]
Dans Geotrek on réutilise les settings django pour l'envoi de mail : https://docs.djangoproject.com/en/3.1/ref/settings/#email

La configuration SMTP que tu as indique qu'il est localement installé. Les erreurs sont corrigées, mais si tu ne reçois pas d'email il peut y avoir 2 raisons :
- soit les mails des managers ne sont pas configurés (voir [la doc](https://geotrek.readthedocs.io/en/master/advanced-configuration.html#email-settings), ce sont simplement les settings django `ADMINS` et `MANAGERS`
- soit le SMTP n'est pas correctement configuré, et là il faut regarder le log du SMTP si le mail est envoyé, s'il y a bien un SMTP installé localement

**Comment by mviadere-openig** [comment]
Ok, j'ai déja configuré  les settings ADMINS et MANAGERS, je vais regarder la deuxième option. Merci à toi.

**Comment by mviadere-openig** [comment]
J'ai pu résoudre le problème grâce au log, merci encore pour ton aide, je clos l'issue.
