### ISSUE TITLE
Prob sync_rando

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#2637]
J'ai testé un passage en 2.55.0 vers 2.55.1.
Cependant mon sync_rando vers mon G.rando n'a pas fonctionné cette nuit, quand je lance mon sync_rando en manuel j'ai le message d'erreur suivant, une idée du problème ? :

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/sync_rando.py", line 511, in handle
    self.sync()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/sync_rando.py", line 380, in sync
    self.sync_tiles()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/sync_rando.py", line 338, in sync_tiles
    self.sync_trek_tiles(trek)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/sync_rando.py", line 138, in sync_trek_tiles
    for (lng, lat) in geom.coords:
TypeError: 'float' object is not iterable

**Comment by gutard** [comment]
Cette erreur arrive quand la géométrie d'une rando est un point alors qu'elle devrait être une linestring. Si tu n'as pas de Geotrek-mobile v2, tu peux préciser l'option --skip-tiles qui accélèrera la synchro et évitera de passer dans le code qui pose problème. Sinon, il faut trouver la rando fautive et la corriger.

En SQL : `SELECT id FROM core_topology WHERE kind='TREK' AND ST_GeometryType(geom)='ST_Point' AND deleted=FALSE;`

**Comment by gutard** [comment]
PAS : a priori ça n'a pas de rapport avec le passage en 2.55.1, ça s'applique à n'importe quelle version.

**Comment by thomaspnrhj** [comment]
Ce qui est bizarre c'est que la synchro du 22/04 en 2.55.0 à marcher alors qu'il n'y a eu aucune modif sur une rando hier, j'aurais donc du avoir l'erreur avant. Ok merci Gaël, je vais essayer de trouve la rando fautive alors...

**Comment by gutard** [comment]
> il n'y a eu aucune modif sur une rando

Ce ne sont pas les modifications sur les randos qui posent problème mais les modifications sur les tronçons.

**Comment by thomaspnrhj** [comment]
Ah ok j'avais mal lu, à priori pas de modif non plus sur les tronçons hier, je regarde ça

**Comment by gutard** [comment]
C'est bien la géométrie d'une rando qui pose problème, mais ça arrive quand on modifie les tronçons, pas la rando elle même (c'est la magie de la segmentation dynamique).

**Comment by camillemonchicourt** [comment]
Si il n'y a eu ni modifications des tronçons ni des randos entre le passage de la 2.55.0 à la 2.55.1, cela ne peut pas indiquer que les randos cassées sous forme de point laissaient quand même passer la synchro en 2.55.0 mais plus en 2.55.1 ?

**Comment by gutard** [comment]
Le code n'a pas changé concernant la synchro donc c'est improbable.
