### ISSUE TITLE
Problème de sync_mobile lors de la récupération de certains profils

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#2662]
Mes commandes de synchronisation des données mobiles n'aboutissent pas, car j'ai des erreurs sur la génération des profils de certaines randonnées. 

Exemple : 

```
** nolang/995141.zip zipped
** nolang/995142/tiles/ downloaded
** nolang/995142/media/paperclip/trekking_trek/995142/44-r.jpg.800x800_q85_watermark-d41d8cd98f00b204e9800998ecf8427e.jpg copied
ERROR 2021-05-19 18:02:11,418 mapentity.helpers Request on http://localhost:6543/?url=http%3A//localhost/api/fr/treks/995142/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=404)
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 139, in download_to_stream
    source = get_source(url, headers)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 124, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://localhost:6543/?url=http%3A//localhost/api/fr/treks/995142/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=404)
Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/api/management/commands/sync_mobile.py", line 508, in handle
    self.sync()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/api/management/commands/sync_mobile.py", line 419, in sync
    self.sync_medias()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/api/management/commands/sync_mobile.py", line 277, in sync_medias
    self.sync_treks_media()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/api/management/commands/sync_mobile.py", line 333, in sync_treks_media
    self.sync_trek_by_pk_media(trek)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/api/management/commands/sync_mobile.py", line 309, in sync_trek_by_pk_media
    trek.prepare_elevation_chart(lang, self.referer)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/altimetry/models.py", line 100, in prepare_elevation_chart
    headers={'Accept-Language': language})
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 198, in convertit_download
    download_to_stream(url, fd, headers=headers)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 139, in download_to_stream
    source = get_source(url, headers)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/mapentity/helpers.py", line 124, in get_source
    assert source.status_code == 200, status_error
AssertionError: Request on http://localhost:6543/?url=http%3A//localhost/api/fr/treks/995142/profile.svg&from=image/svg%2Bxml&to=image/png failed (status=404)
```

En effet pour cette rando, j'ai bien le profil dans la fiche détail, la rando n'a pas de soucis, mais le fichier de son profil dans le dossier ``/opt/geotrek-admin/var/media/profiles/`` fait 0 ko..

![Capture d’écran de 2021-05-19 18-12-16](https://user-images.githubusercontent.com/4418840/118847746-5b54f400-b8ce-11eb-9609-7c31895bafaf.png)

Je l'ai supprimé du dossier et relancé la commande ``sync_mobile``, le fichier s'est recréé en faisant toujours 0 ko et donc la commande de synchro a de nouveau bloqué sur la récupération du profil de cette rando.

![Capture d’écran de 2021-05-19 18-13-52](https://user-images.githubusercontent.com/4418840/118847767-63ad2f00-b8ce-11eb-9c48-a2302d34f070.png)

J'ai aussi essayé de modifier un peu le tracé de la rando, de supprimer le PNG du profil et de relancer la synchro mobile, mais toujours le même soucis.

Je ne sais pas pourquoi la génération du profil a un soucis sur cette rando et ce qui pourrait le corriger ?

**Comment by submarcos** [comment]
Bonjour Camille,
Au niveau de l'erreur on voit le code 404, ce qui signifie que convertit n'arrive tout simplement pas à accéder au profil svg.
Il faudrait vérifier que le profil est bien accessible avec l'url http://localhost/api/fr/treks/995142/profile.svg . Peut etre qu'une configuration qui a changé fait que le site n'est pas accessible sous http://localhost (peut etre lié à une modification du fichier default de nginx ?) Auquel cas il suffirait de fixer en utilisant le parametre url de la commande sync_mobile pour remplacer http://locahost par l'url de l'admin

**Comment by camillemonchicourt** [comment]
OK merci pour ces précisions.
Je ne savais pas qu'on pouvait/devait aussi préciser l'option ``--url`` pour la commande ``sync_mobile``.
Je viens d'ajouter cette option à ma commande ``sync_mobile`` en spécifiant l'URL de mon Geotrek-admin et la synchro mobile est bien passée en générant les profils comme il faut. Merci.

Suite au ticket https://github.com/GeotrekCE/Geotrek-admin/issues/2623, j'avais identifié que j'avais bien une configuration NGINX ``default`` mais que celle-ci n'était pas activée.
Je l'ai activée le 28 avril 2021, pour ne plus avoir plein d'alertes mais ça n'a pas arrangé les choses, et c'est peut-être depuis cela que la génération des profils sur http://localhost ne fonctionne plus.
Mais c'est un autre sujet, que je dois creuser.
