### ISSUE TITLE
Erreur pendant la commande sudo dpkg-reconfigure Geotrek-admin

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-admin#2723]
Geotrek-admin v2.62.0

Voici ce qui se passe après avoir renseigné le dernier champ pendant la commande sudo dpkg-reconfigure geotrek-admin

Generate configuration
Migrate database
Update objects translation after migration from .po files
Lang : fr
TargetPortal
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/update_post_migration_languages.py", line 26, in execute
    ).update(**{'title_{}'.format(lang): _('Geotrek Rando')})
  File "/opt/geotrek-admin/lib/python3.6/site-packages/modeltranslation/manager.py", line 345, in update
    return super(MultilingualQuerySet, self).update(**kwargs)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/query.py", line 784, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1522, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(50)

Copy static files
Reload

Cela n'empêche pas pour autant le Geotrek-admin de fonctionner. Des idées ?

**Comment by camillemonchicourt** [comment]
Vu dans le message d'erreur : 
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)

Il semblerait que tu renseignes un champs dont la valeur est limitée à 50 caractères, avec une valeur supérieure à 50 ?

**Comment by mviadere-openig** [comment]
Oui, ça je l'avais bien compris, mais je n'ai aucune idée de quel champ il s'agit. Est-ce que c'est un champ qui dans la configuration, dans la base de donnée ?

**Comment by mviadere-openig** [comment]
J'ai regardé un à un les différents appel de fichier. Celui-ci `File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/update_post_migration_languages.py", line 26, in execute` laissait comprendre que l'erreur viendrait d'un titre trop long dans la traduction du titre dans `/opt/geotrek-admin/var/conf/extra_locale/fr/LC_MESSAGES/django.po`. Je l'ai modifié, puis j'ai appliqué les changements de traductions, j'ai relancé `sudo dpkg-reconfigure geotrek-admin` et le problème a disparu.. je clos l'issue.

**Comment by camillemonchicourt** [comment]
OK donc c'était dans la surcouche des fichiers de langue. 
Il faudrait certainement remonter la limite pour ne pas limiter à 50 caractères ?
