### ISSUE TITLE
Mise à jour 2.76.2

### ISSUE THREAD

**Issue by jeromesourdin** [GeotrekCE/Geotrek-admin#2956]
Bonjour, j'ai fait la mise à jour de notre geotrek-admin, et j'ai une petite erreur  
```
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column "accessibility_infrastructure_fr" does not exist
LINE 1: ...nfrastructure_fr=disabled_infrastructure_fr WHERE accessibil...
                                                             ^
HINT:  Perhaps you meant to reference the column "trekking_trek.accessibility_infrastructure".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/migrate.py", line 25, in handle
    super().handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/trekking/migrations/0039_move_traduction_disabled_infrastructure_equipment.py", line 14, in forward
    cursor.execute(f"UPDATE trekking_trek SET accessibility_infrastructure_{lang}=disabled_infrastructure_{lang} WHERE accessibility_infrastructure_{lang} = '';")
  File "/opt/geotrek-admin/lib/python3.6/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "accessibility_infrastructure_fr" does not exist
LINE 1: ...nfrastructure_fr=disabled_infrastructure_fr WHERE accessibil...
                                                             ^
HINT:  Perhaps you meant to reference the column "trekking_trek.accessibility_infrastructure".
```
Cela ne semble pas perturber le fonctionnement, mais je m'interroge...

**Comment by camillemonchicourt** [comment]
OK merci pour le retour.
On voit ce que c'est. @LePetitTim regarde ça.
On travaille en ce moment sur l'ajout de pas mal de champs liés à l'accessibilité des itinéraires aux PMR : https://github.com/GeotrekCE/Geotrek-admin/issues/2838

On en profite pour faire du ménage et mettre en cohérence les noms de champs et c'est ainsi qu'on a renommé le champs ``disabled_infrastructure`` en ``accessibility_infrastructure`` dans la table ``trekking_trek`` et c'est là qu'il y a un cas à revoir dans les migrations de données.

**Comment by camillemonchicourt** [comment]
C'est corrigé et testé en 2.76.3.
Les prochains n'auront pas le soucis que tu as rencontré et toi tu peux faire une nouvelle mise à jour pour passer sur la 2.76.3.

**Comment by jeromesourdin** [comment]
Je viens de faire une nouvelle mise à jour, et j'ai une autre erreur du a une vue perso : 
```
Migrate database
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DependentObjectsStillExist: cannot drop table trekking_trek column disabled_infrastructure_fr because other objects depend on it
DETAIL:  view v_treks_cd22 depends on table trekking_trek column disabled_infrastructure_fr
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/common/management/commands/migrate.py", line 25, in handle
    super().handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/geotrek/trekking/migrations/0040_remove_translation_equipment_disabled_infrastructure.py", line 14, in forward
    cursor.execute(f"ALTER TABLE trekking_trek DROP COLUMN disabled_infrastructure_{lang};")
  File "/opt/geotrek-admin/lib/python3.6/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.InternalError: cannot drop table trekking_trek column disabled_infrastructure_fr because other objects depend on it
DETAIL:  view v_treks_cd22 depends on table trekking_trek column disabled_infrastructure_fr
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```
J'ai corrigé ma vue et refait une install, et c'est bien passer ! Faudra que pense a vérifier à l'avenir ;) !

**Comment by camillemonchicourt** [comment]
Oui en effet, comme on a changé le nom de ce champs, si il est utilisé dans des vues spécifiques, alors il faut le renommer.
Mais c'est très rare et on évite de renommer des champs, mais là comme on travaillait sur l'ajout de plusieurs champs liés à l'accessibilité, il était pertinent de mettre en cohérence ceux déjà existant.

Par contre, on n'a pas changé le nom de la propriété ``disabled_infrastructure`` dans l'API v2 car là on est moins certain qu'elle ne soit pas utilisé par des outils tiers.
