### ISSUE TITLE
Problème sync_mobile

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-admin#3170]
On vient de se rendre compte que notre G.admin ne synchronise plus pour l'appli, voici le log, je suis preneur si quelqu'un a déjà rencontré ce problème ou si quelque'un connait l'origine :
Merci et à bientôt,
Thomas 

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/api/management/commands/sync_mobile.py", line 516, in handle
    self.sync()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/api/management/commands/sync_mobile.py", line 427, in sync
    self.sync_medias()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/api/management/commands/sync_mobile.py", line 280, in sync_medias
    self.sync_global_media()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/api/management/commands/sync_mobile.py", line 358, in sync_global_media
    self.sync_pictograms(trekking_models.DifficultyLevel, directory=url_media_nolang, zipfile=self.zipfile_settings)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/api/management/commands/sync_mobile.py", line 189, in sync_pictograms
    cairosvg.svg2png(url=obj.pictogram.path, write_to=dst)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/cairosvg/surface.py", line 127, in convert
    tree = Tree(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/defusedxml/common.py", line 131, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1693, in feed
    self.parser.Parse(data, 0)
  File "../Modules/pyexpat.c", line 481, in EntityDecl
  File "/opt/geotrek-admin/lib/python3.8/site-packages/defusedxml/ElementTree.py", line 113, in defused_entity_decl
    raise EntitiesForbidden(name, value, base, sysid, pubid, notation_name)
defusedxml.common.EntitiesForbidden: EntitiesForbidden(name='ns_svg', system_id=None, public_id=None)

**Comment by submarcos** [comment]
Hello, on dirait plutot un probleme de sync_mobile que de sync_rando.

Vu l'erreur, on dirait que çà plante sur la conversion d'un picto svg en png. Un picto aurait-il été changé recemment ? c'est surement lui le fautif

**Comment by thomaspnrhj** [comment]
@submarcos oui sync_mobile pardon
Oui il y a eu quelques changements avec le passage à la V3, je vais regarder ça merci

**Comment by camillemonchicourt** [comment]
Oui ça ressemble à plusieurs tickets assez proches, mais je trouve rien de similaire : 
- https://github.com/GeotrekCE/Geotrek-admin/search?q=sync_mobile+png&type=issues
- https://github.com/GeotrekCE/Geotrek-admin/issues/3122

**Comment by thomaspnrhj** [comment]
En lançant la commande de Gael conseillé sur https://github.com/GeotrekCE/Geotrek-admin/issues/2441 à savoir sudo journalctl -eu convertit, on a le log suivant : 

juil. 05 09:53:26 randoadmin.parc-haut-jura.fr inkscape[1443682]: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed
juil. 05 09:53:26 randoadmin.parc-haut-jura.fr inkscape[1443682]: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed
juil. 05 09:53:26 randoadmin.parc-haut-jura.fr inkscape[1443682]: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
juil. 05 09:53:26 randoadmin.parc-haut-jura.fr pserve[1443682]: Failed to get connectionBackground RRGGBBAA: ffffff00
juil. 05 09:53:26 randoadmin.parc-haut-jura.fr pserve[1443682]: Area 0:0:800:400 exported to 800 x 400 pixels (96 dpi)
juil. 05 09:53:26 randoadmin.parc-haut-jura.fr pserve[1443682]: Bitmap saved as: /var/cache/convertit/converted/profile.png

on a vérifier les profils, vider /opt/geotrek-admin/var/media/profiles mais rien n'y fait...

**Comment by camillemonchicourt** [comment]
En creusant ton erreur et en regardant au niveau de la librairie CairoSVG qui est utilisée, on tombe sur https://github.com/Kozea/CairoSVG/issues/338

Cela confirme un soucis au niveau de la structure de ton SVG.

Reprends le dans Inkscape et ça devrait le faire je dirai.

**Comment by thomaspnrhj** [comment]
Merci @camillemonchicourt c'est bien ça 👍

Pour identifier le svg qui pose problème : ouvrir le svg en format texte et dans l'entête identifier un bloc similaire 
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [
	<!ENTITY ns_svg "http://www.w3.org/2000/svg">
	<!ENTITY ns_xlink "http://www.w3.org/1999/xlink">

Pour résoudre le problème : ouvrir le svg sur inkscape, enregistrer un copie en svg optimisé
