### ISSUE TITLE
Erreur au lancement d'une 2.84.1 docker toute fraîche (erreur de version de dépendance `paperclip` ?)

### ISSUE THREAD

**Issue by seegwen** [GeotrekCE/Geotrek-admin#3172]
Je fais un clone frais du repo.

Puis, comme spécifié dans la doc (https://geotrek.readthedocs.io/en/2.84.1/install/docker.html):
````
mv .env-dev.dist .env
docker-compose run --rm web update.sh
````
Et la console me renvoit une erreur:

````
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/venv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/venv/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/geotrek-admin/geotrek/common/models.py", line 13, in <module>
    from paperclip.models import Attachment as BaseAttachment, FileType as BaseFileType, License as BaseLicense
ImportError: cannot import name 'License' from 'paperclip.models' (/opt/venv/lib/python3.8/site-packages/paperclip/models.py)
````

**Comment by LePetitTim** [comment]
J'ai testé je n'ai pas le problème.

Est ce que vous avez modifié l'ordre des settings installed_apps ?

**Comment by seegwen** [comment]
Bonjour, je ne sais pas pourquoi je n'avais pas eu de notification de réponse à ce thread (et donc pas vu la réponse de @submarcos). D'où mon silence. Désolé pour ça... 😞 

Entre-temps je suis resté sur ma `2.82`, puis il y a deux jours j'ai fait un upgrade de mon repo pour passer au dernier tag `2.86`. Avec succès (je vous passe les détails - pb de connexion à pgsql).

Donc je n'ai pas testé le process de @submarcos, peut-être cela aurait profité à d'autres.
Merci pour vos réponses en tout cas. 👍
