### ISSUE TITLE
Error to delete Path

### ISSUE THREAD

**Issue by gzileni** [GeotrekCE/Geotrek-admin#3259]
```
Environment:


Request Method: POST
Request URL: http://localhost:8000/path/delete/1/

Django Version: 3.2.15
Python Version: 3.8.10
Installed Applications:
('django_extensions',
 'debug_toolbar',
 'drf_yasg',
 'modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.gis',
 'crispy_forms',
 'compressor',
 'django_filters',
 'tinymce',
 'easy_thumbnails',
 'mapentity',
 'paperclip',
 'leaflet',
 'rest_framework',
 'rest_framework_gis',
 'embed_video',
 'django_celery_results',
 'colorfield',
 'mptt',
 'geotrek.cirkwi',
 'geotrek.authent',
 'geotrek.common',
 'geotrek.altimetry',
 'geotrek.core',
 'geotrek.infrastructure',
 'geotrek.signage',
 'geotrek.maintenance',
 'geotrek.zoning',
 'geotrek.land',
 'geotrek.trekking',
 'geotrek.tourism',
 'geotrek.flatpages',
 'geotrek.feedback',
 'geotrek.api')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'geotrek.authent.middleware.LocaleForcedMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'geotrek.common.middleware.APILocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'geotrek.authent.middleware.CorsMiddleware',
 'mapentity.middleware.AutoLoginMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')



Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (column "published_it" of relation "trekking_trek" does not exist
LINE 2:             SET published_it = FALSE
                        ^
QUERY:  UPDATE trekking_trek i
            SET published_it = FALSE
            FROM core_pathaggregation et
            WHERE et.topo_object_id = i.topo_object_id AND et.path_id = OLD.id
CONTEXT:  PL/pgSQL function paths_unpublish_trek_d() line 12 at SQL statement
) was the direct cause of the following exception:
  File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/geotrek-admin/geotrek/authent/decorators.py", line 18, in _wrapped_view
    result = view_func(self, request, *args, **kwargs)
  File "/opt/geotrek-admin/geotrek/core/views.py", line 220, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/mapentity/decorators.py", line 61, in _wrapped_view
    return decorated(self, request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/mapentity/decorators.py", line 59, in decorated
    return view_func(self, request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/mapentity/views/generic.py", line 461, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/views/generic/edit.py", line 218, in post
    return self.delete(request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/mapentity/views/generic.py", line 469, in delete
    return super().delete(request, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/views/generic/edit.py", line 213, in delete
    self.object.delete()
  File "/opt/geotrek-admin/geotrek/core/models.py", line 273, in delete
    r = super().delete(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/mapentity/models.py", line 142, in delete
    super().delete(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 429, in delete
    count = query.delete_batch(pk_list, self.using)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 43, in delete_batch
    num_deleted += self.do_query(self.get_meta().db_table, self.where, using=using)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/subqueries.py", line 23, in do_query
    cursor = self.get_compiler(using).execute_sql(CURSOR)
  File "/opt/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 205, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/opt/venv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 140, in _record
    return method(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /path/delete/1/
Exception Value: column "published_it" of relation "trekking_trek" does not exist
LINE 2:             SET published_it = FALSE
                        ^
QUERY:  UPDATE trekking_trek i
            SET published_it = FALSE
            FROM core_pathaggregation et
            WHERE et.topo_object_id = i.topo_object_id AND et.path_id = OLD.id
CONTEXT:  PL/pgSQL function paths_unpublish_trek_d() line 12 at SQL statement


```

**Comment by camillemonchicourt** [comment]
OK, so the error is 
```
column "published_it" of relation "trekking_trek" does not exist
LINE 2:  SET published_it = FALSE``
```

So what I understand is that you are trying to delete a path. 
This path is used by a trek.
When deleting a path used by a trek (or another topology releated to path) it don't delete this trek but it unpublish the trek will be broken by this trek removal.
But in your case, when trying to unpublish this trek (using the path your are trying to delete), the database can't find the field ``published_it`` that it is trying to updated to set to ``false``.

I don't understand why you don't have this field ``published_it`` in the ``trekking_trek`` table. 
It seems that there is a problem.

But one workaround of this problem is to edit this trek before so that it doesn't use this path and then you should be able to remove this path.

But it would be interesting to understand why you don't have this field.

Can you check in your database, in ``trekking_trek``table that you don't have this ``published_it`` field ?
Did you add the ITALIAN language before the initial installation of Geotrek-admin, or you added it to your configuration later ?
You activated

**Comment by camillemonchicourt** [comment]
I just tried to reproduce it.
I created a new trek using 3 paths and published it.
I deleted one of the paths used by this trek.
The deletion of the path worked well and the trek using it was well unpublished.

So no problem in my case.

**Comment by submarcos** [comment]
Problem is that Italian language was added after database initialization.
Language can't be added after initialization if data is present in tables because of "published column" are boolean, and django-modeltranslation does not provide default values for it. I suggest to delete Italian from language, or reinit a database with this language, or, by hand, add missing columns directly in database in all tables with published is used, and run dpkg-reconfigure or update.sh to validate.
