### ISSUE TITLE
Signalétique - Topologie non valide

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3390]
Lors de la création d'une signalétique, parfois trois `core_pathaggregation` sont créées avec trois `path_id` différents, mais chacune la valeur 0 dans la colonne `order`. Ce problème fait remonter la signalétique dans le filtre "Topologie non valide" de Geotrek-admin, ce qui est logique.
Si je modifie la géométrie via l'interface Django, le problème est réglé et il n'y a plus qu'une `core_pathaggregation` présente, la topologie est donc considérée comme valide.

Problème : pourquoi est-ce que Geotrek-admin crée plusieurs `core_pathaggregation` de lui-même pour une géométrie ponctuelle, sans les ordonner correctement qui plus est ?

Question annexe : est-il possible de déclencher le recalcul des `core_pathaggregation` en SQL, à partir de la géométrie d'une `core_topology` ? Aucune de mes tentatives n'a permis de déclencher ça, ni en cherchant parmi les triggers, ni parmi les fonctions.

**Comment by camillemonchicourt** [comment]
Je pense que c'est un cas particulier souhaité.

Si une topologie ponctuelle est pile à une intersection de tronçons, alors on veut que celle-ci soit associée aux 3 tronçons, et pas seulement à une des 3 tronçons.

**Comment by jeromesourdin** [comment]
Bonjour,
Le script de correction de topologies ne fonctionne pas dans ce cas ? `sudo geotrek reorder_topologies`
https://geotrek.readthedocs.io/en/2.94.0/install/import.html#reorder-topologies

**Comment by IdrissaD** [comment]
> 

> Je pense que c'est un cas particulier souhaité.
> 
> Si une topologie ponctuelle est pile à une intersection de tronçons, alors on veut que celle-ci soit associée aux 3 tronçons, et pas seulement à une des 3 tronçons.

Les signalétiques sur lesquels j'ai vu le cas n'étaient pas à des intersections de tronçons, mais en-dehors du réseau, c'est eut-être ça un des problèmes ?

> Bonjour, Le script de correction de topologies ne fonctionne pas dans ce cas ? `sudo geotrek reorder_topologies` https://geotrek.readthedocs.io/en/2.94.0/install/import.html#reorder-topologies

Ah merci, je ne connaissais pas cette commande ! Malheureusement elle me donne une erreur : 
```
Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/core/management/commands/reorder_topologies.py", line 84, in handle
    next_point_start = GEOSGeometry(geom_lines[order_next][1], srid=settings.SRID).boundary[
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/contrib/gis/geos/mutable_list.py", line 77, in __getitem__
    index = self._checkindex(index)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/contrib/gis/geos/mutable_list.py", line 235, in _checkindex
    raise IndexError('invalid index: %s' % index)
IndexError: invalid index: 0
```
