### ISSUE TITLE
Bug : Cadre rouge autour de fenêtre carto

### ISSUE THREAD

**Issue by julienchaudet** [GeotrekCE/Geotrek-admin#3535]
Bonjour,
Je rencontre un bug : un cadre rouge apparait autour de la fenêtre de visualisation de la carte, et les entités de la liste n'y apparaissent plus.
Ce phénomène se produit aléatoirement, le plus souvent lorsque je ferme un onglet entité et que je reviens au module.
Le seul moyen de faire disparaitre ce cadre rouge est de me déconnecter et reconnecter à geotrek admin.
Avez-vous déjà constaté ce problème ? J'ai cherché je n'ai pas trouvé de sujet qui l'abordait.

![Annotation 2023-03-28 151916](https://user-images.githubusercontent.com/129185394/228251445-44974cd7-6e41-4ac3-b2dc-b59b0bef9a59.jpg)

**Comment by babastienne** [comment]
Généralement le cadre rouge implique qu'il y a un problème de chargement du geojson dans l'interface, les traces ne peuvent donc pas être affichées. Reste à savoir pourquoi il y a ce problème ...

Quelle est la version de Geotrek-Admin utilisée ?

**Comment by camillemonchicourt** [comment]
Je pense que ça peut-être un Geotrek-admin mis à jour, dans avoir vidé le cache serveur comme indiqué dans des versions récentes.

**Comment by julienchaudet** [comment]
Merci, nous sommes en Version 2.97.4
Je vais faire remonter l'info à notre nouveau chef SI, je reviendrai confirmer si ça règle le problème.

**Comment by vprunet** [comment]
Je pense avoir vidé les trois caches après la mise à jour en 2.97.4, comme indiqué dans les release notes et expliqué par Camille. Mais j'ai pu en oublier un. Je viens de le refaire.

Voici par ailleurs ce que j'ai trouvé de significatif dans les log récents.
```
WARNING 2023-03-24 16:05:59,548 root Could not resolve form field 'topology'.
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'topology'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'topology' not found in 'InterventionForm'. Choices are: date, description, disorders, height, heliport_cost, length, material_cost, name, project, stake, status, structure, subcontract_cost, subcontracting, type, width."
WARNING 2023-03-24 16:08:11,349 root Could not resolve form field 'topology'.
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'topology'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'topology' not found in 'InterventionForm'. Choices are: date, description, disorders, height, heliport_cost, length, material_cost, name, project, stake, status, structure, subcontract_cost, subcontracting, type, width."
WARNING 2023-03-24 16:08:44,946 root Could not resolve form field 'topology'.
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'topology'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'topology' not found in 'InterventionForm'. Choices are: date, description, disorders, height, heliport_cost, length, material_cost, name, project, stake, status, structure, subcontract_cost, subcontracting, type, width."
```
```
WARNING 2023-03-28 10:48:49,577 root Could not resolve form field 'structure'.
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'structure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'structure' not found in 'InfrastructureForm'. Choices are: accessibility_de, accessibility_en, accessibility_fr, accessibility_it, condition, description_de, description_en, description_fr, description_it, implantation_year, maintenance_difficulty, name_de, name_en, name_fr, name_it, topology, type, usage_difficulty."
WARNING 2023-03-28 10:56:16,065 root Could not resolve form field 'structure'.
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 153, in __getitem__
    field = self.fields[name]
KeyError: 'structure'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/crispy_forms/utils.py", line 70, in render_field
    bound_field = form[field]
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/forms/forms.py", line 155, in __getitem__
    raise KeyError(
KeyError: "Key 'structure' not found in 'InfrastructureForm'. Choices are: accessibility_de, accessibility_en, accessibility_fr, accessibility_it, condition, description_de, description_en, description_fr, description_it, implantation_year, maintenance_difficulty, name_de, name_en, name_fr, name_it, topology, type, usage_difficulty."

```

**Comment by camillemonchicourt** [comment]
Naïvement en regardant les logs, on dirait que des interventions n'ont pas de topologie et/ou de structure ?
Les logs sont toujours les mêmes ?

**Comment by babastienne** [comment]
Est-ce que le problème est toujours d'actualité ?

**Comment by julienchaudet** [comment]
Bonjour,
Le problème n'apparait plus sur ma session mais est apparu depuis le compte utilisateur d'une collègue, récemment.

**Comment by raphaeldoisy** [comment]
Bonjour,
Du temps a passé sous les ponts, est-ce toujours d'actualité aussi ?

**Comment by julienchaudet** [comment]
Bonjour,
Pas eu de problème reporté depuis 2024 donc on peut considérer que la manip de vider les caches a fonctionné.

**Comment by raphaeldoisy** [comment]
Merci Julien pour ta réponse! Je ferme donc ce ticket.
