### ISSUE TITLE
Cannot use shape file on Imports page

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#3574]
Constaté en `v2.96.1` et `v2.98.0`.

**Description**

Utiliser un fichier shape file pour importer des communes ou des zones sensibles depuis le formulaire de la page Imports ne fonctionne pas. L'import fonctionne avec un fichier geojson.

**Pour reproduire :** sélectionner un fichier shape dans le formulaire et cliquer "Importer".

![Capture d’écran du 2023-04-21 11-22-03](https://user-images.githubusercontent.com/15977920/233605403-2a8440e0-3f83-437e-81d5-627d00041659.png)

**Traceback erreur :**

```
GDAL_ERROR 4: b'Unable to open /opt/geotrek-admin/var/tmp/test/test.shx or /opt/geotrek-admin/var/tmp/test/test.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.'
[2023-04-21 09:45:39,082: ERROR/ForkPoolWorker-1] GDAL_ERROR 4: b'Unable to open /opt/geotrek-admin/var/tmp/test/test.shx or /opt/geotrek-admin/var/tmp/test/test.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.'
[2023-04-21 09:45:39,087: ERROR/ForkPoolWorker-1] Task geotrek.common.import-file[bc2587af-035a-4d8b-92e5-130fd4841c59] raised unexpected: GDALException('Could not open the datasource at "/opt/geotrek-admin/var/tmp/test/test.shp"')
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/gis/gdal/datasource.py", line 71, in __init__
    ds = capi.open_ds(force_bytes(ds_input), self._write, byref(ds_driver))
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/gis/gdal/prototypes/errcheck.py", line 127, in check_pointer
    raise GDALException('Invalid pointer returned from "%s"' % func.__name__)
django.contrib.gis.gdal.error.GDALException: Invalid pointer returned from "OGROpen"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/geotrek-admin/geotrek/common/tasks.py", line 78, in import_datas
    raise e
  File "/opt/geotrek-admin/geotrek/common/tasks.py", line 76, in import_datas
    parser.parse(filename)
  File "/opt/geotrek-admin/geotrek/common/parsers.py", line 534, in parse
    for i, row in enumerate(self.next_row()):
  File "/opt/geotrek-admin/geotrek/common/parsers.py", line 599, in next_row
    datasource = DataSource(self.filename, encoding=self.encoding)
  File "/opt/venv/lib/python3.8/site-packages/django/contrib/gis/gdal/datasource.py", line 75, in __init__
    raise GDALException('Could not open the datasource at "%s"' % ds_input)
django.contrib.gis.gdal.error.GDALException: Could not open the datasource at "/opt/geotrek-admin/var/tmp/test/test.shp"
```

**Fonctionnement attendu :** l'import à partir d'un shapefile fonctionne.

**Piste :** regarder si les changements sur la fonction `geotrek.common.views.import_file` en 2.94.0 peuvent être en cause ([commit](https://github.com/GeotrekCE/Geotrek-admin/commit/dda4b15611fdab849d7ba45375647773c946a9c2)).

**Keywords :** CityParser, SpeciesSensitiveAreaShapeParser, RegulatorySensitiveAreaShapeParser

**Comment by babastienne** [comment]
Il me semble que lorsqu'on veut importer un fichier shp via cette commande il faut en réalité importer un zip qui contient les fichiers .shp .shx. .prj .dbf .cpg.

C'est comme ça que tu as essayé de faire l'import ou tu as juste essayé d'importer le fichier .shp ?

**Comment by marcantoinedupre** [comment]
Bien vu ! Non, j'avais testé sans le zip en sélectionnant uniquement le fichier `.shp` (évidemment il manque des infos).

Je renomme ce ticket et je retire le label `bug`.

À faire :

- a minima : ajouter dans la doc qu'il faut zipper les fichiers composant le shapefile.
- top : l'indiquer dans l'UI et essayer de détecter les mauvais usages pour retourner une erreur pertinente.

**Comment by bruhnild** [comment]
https://github.com/GeotrekCE/Geotrek-admin/pull/3890/commits/2628cebdbf242d7f302857d155a235e50e27a7ed
