### ISSUE TITLE
Commande `loadsignage` - erreur sur valeurs nulles du champ `year`

### ISSUE THREAD

**Issue by IdrissaD** [GeotrekCE/Geotrek-admin#3611]
Quand je lance la commande `docker-compose run --rm web ./manage.py loadsignage --structure-field structure --name-field name --type-field type --manager-field manager --sealing-field sealing --description-field description --code-field code --eid-field eid --year-field year signaletique.gpkg`, si le champ `year` est nul pour certaines signalétiques, l'erreur suivante survient : 
``` python
An error occured, rolling back operations.
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/geotrek/signage/management/commands/loadsignage.py", line 181, in handle
    year = int(feature.get(field_implantation_year)) if field_implantation_year in available_fields and feature.get(field_implantation_year).isdigit() else default_year
AttributeError: 'NoneType' object has no attribute 'isdigit'
```

Pas d'erreur si je remplace toutes les valeurs nulles par 0.

**Comment by camillemonchicourt** [comment]
Corrigé dans la 2.101.0
