### ISSUE TITLE
Erreur 500 suite à mise à jour vers 2.100.1

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-admin#3719]
Suite à la mise à jour vers la version 2.100.1, j'obtiens une erreur 500 lorsque je tente d'accéder à n'importe quelle page objet.

Le fichier de log mentionne la ligne suivante : 

```
Sep 11 09:53:51 geotrek-2 gunicorn[46778]: django.db.utils.ProgrammingError: column tourism_touristicevent.organizer_id does not exist
Sep 11 09:53:51 geotrek-2 gunicorn[46778]: LINE 1: ...ent"."email", "tourism_touristicevent"."website", "tourism_t...
Sep 11 09:53:51 geotrek-2 gunicorn[46778]:                                                              ^
Sep 11 09:53:51 geotrek-2 gunicorn[46778]: HINT:  Perhaps you meant to reference the column "tourism_touristicevent.organizer".
```

Lorsque je lance une synchro, cela génère également le même type d'erreur : 

```
fr meta/fr/index.html failed (column tourism_touristicevent.organizer_id does not exist
LINE 1: ...ent"."email", "tourism_touristicevent"."website", "tourism_t...
                                                             ^
HINT:  Perhaps you meant to reference the column "tourism_touristicevent.organizer".
)
```

Cela semble lié à #3625.

**Comment by babastienne** [comment]
En effet cela semble lié au développement sur les organisateurs d'évènements.

Il nous faudrait les logs complets pour pouvoir mieux identifier l'erreur. 

Est-ce que la migration s'était bien déroulée ou des messages d'erreurs étaient apparus dans la console ?

**Comment by pnrma** [comment]
Voilà les logs lors de la migration :

```
Generate configuration
Migrate database
Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
__fake__.DoesNotExist: TouristicEventOrganizer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(128)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/management/commands/migrate.py", line 14, in handle
    super().handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/tourism/migrations/0044_deplace_organizer_to_model.py", line 11, in create_organizer_fk
    organizer, _ = OrganizerModel.objects.get_or_create(label=event.organizer)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(128)

Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Update objects translation after migration from .po files
Lang : fr
TargetPortal
Label is park centered
Lang : en
TargetPortal
Label is park centered
Done.
Copy static files
Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Reload
```

**Comment by pnrma** [comment]
Et voilà les logs générés par sudo journalctl -eu geotrek-ui :


```
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: ERROR 2023-09-11 10:23:57,824 django.request Internal Server Error: /site/2/
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: Traceback (most recent call last):
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.cursor.execute(sql, params)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: psycopg2.errors.UndefinedColumn: column tourism_touristicevent.organizer_id does not exist
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: LINE 1: ...ent"."email", "tourism_touristicevent"."website", "tourism_t...
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:                                                              ^
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: HINT:  Perhaps you meant to reference the column "tourism_touristicevent.organizer".
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: The above exception was the direct cause of the following exception:
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: Traceback (most recent call last):
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     response = get_response(request)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     response = response.render()
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/response.py", line 105, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     self.content = self.rendered_content
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return template.render(context, self._request)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.template.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 170, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return compiled_parent._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return compiled_parent._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return compiled_parent._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return compiled_parent._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 988, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     output = self.filter_expression.resolve(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     obj = self.var.resolve(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     value = self._resolve_lookup(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     current = current()
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 76, in super
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return mark_safe(self.render(self.context))
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return template.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 172, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return compiled_parent._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 988, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     output = self.filter_expression.resolve(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     obj = self.var.resolve(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     value = self._resolve_lookup(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     current = current()
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 76, in super
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return mark_safe(self.render(self.context))
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result = block.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/templatetags/mapentity_tags.py", line 37, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     result += t.render(Context.flatten(context))
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.template.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 170, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self._render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/defaulttags.py", line 315, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return nodelist.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 938, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     bit = node.render_annotated(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.render(context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/template/library.py", line 214, in render
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     _dict = self.func(*resolved_args, **resolved_kwargs)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/mapentity/templatetags/mapentity_tags.py", line 140, in valuelist
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     itemslist = [display(v) for v in items]
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     self._fetch_all()
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     self._result_cache = list(self._iterable_class(self))
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     cursor.execute(sql, params)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return executor(sql, params, many, context)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.cursor.execute(sql, params)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:   File "/opt/geotrek-admin/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:     return self.cursor.execute(sql, params)
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: django.db.utils.ProgrammingError: column tourism_touristicevent.organizer_id does not exist
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: LINE 1: ...ent"."email", "tourism_touristicevent"."website", "tourism_t...
Sep 11 10:24:01 geotrek-2 gunicorn[1265]:                                                              ^
Sep 11 10:24:01 geotrek-2 gunicorn[1265]: HINT:  Perhaps you meant to reference the column "tourism_touristicevent.organizer".

```

**Comment by babastienne** [comment]
Ok, donc la migration ne s'est pas déroulée correctement. 

Pour résumer, la 2.100 a modifié la notion d'organisateur d'évènements. Auparavant c'était un champ texte libre qui est passé d'une valeur maximale de 128 caractères à 256. Or le cas d'une valeur supérieure à 128 caractères a été mal géré et donc, à priori, plante.

Il faut qu'on corrige cette migration je pense. En attendant à court terme pour vous débloquer vous pouvez dans la base de données supprimer (ou modifier) les champ "Organisateur" des évènements touristiques qui sont plus long que 128 caractères, et ensuite la migration se passera correctement.

**Comment by pnrma** [comment]
Ok merci.
Il y avait effectivement un événement touristique (public.tourism_touristicevent) dont le champ `organizer` dépassait les 128 caractères.
En modifiant ce champ et en relançant la commande `sudo dpkg-reconfigure geotrek-admin`, cela ne génère plus d'erreur.

**Comment by babastienne** [comment]
Ok parfait. 

Un hotfix vient d'être créé, la prochaine release de Geotrek corrigera le problème pour que d'autres territoires ne soient pas obligés d'effectuer cette manipulation. 

Merci d'avoir remonté ce bug. :pray:
