### ISSUE TITLE
Parseur Esprit Parc - Erreur 403

### ISSUE THREAD

**Issue by amandine-sahl** [GeotrekCE/Geotrek-admin#3861]
Suite à une évolution des règles de sécurité du serveur Esprit Parc, les appels à l'API sont bloquées si aucun User-Agent n'est spécifié.
Il faudrait modifier le parseur en conséquence de façon pouvoir à ajouter des paramètres headers.

```python
headers = { "User-Agent": "Geotrek"  }
```

**Comment by Chatewgne** [comment]
Merci pour l'information, nous avions remarqué des erreurs avec ces parsers mais manquions de visibilité sur la cause.

**Comment by camillemonchicourt** [comment]
Oui et donc rendre le header surcouchable sur chaque parser.

**Comment by camillemonchicourt** [comment]
Bon, j'ai un petit effet de bord de l'ajout d'un "header" dans les appels des parsers, mais il est lié à un parser qui nous est spécifique, pour récupérer les ID des itinérances réservables depuis Open System (Alliance Réseaux) : 

```
==== Import Reservation Open System
Read env configuration from /opt/geotrek-admin/lib/python3.8/site-packages/geotrek/settings/env_prod.py
Read custom configuration from /opt/geotrek-admin/var/conf/custom.py
Traceback (most recent call last):
  File "/usr/sbin/geotrek", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/management/commands/import.py", line 55, in handle
    parser.parse(options['filename'], limit=limit)
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 541, in parse
    for i, row in enumerate(self.next_row()):
  File "/opt/geotrek-admin/var/conf/parsers.py", line 37, in next_row
    response = self.request_or_retry(self.url, headers={'Authorization': self.api_key})
  File "/opt/geotrek-admin/lib/python3.8/site-packages/geotrek/common/parsers.py", line 564, in request_or_retry
    response = action(url, headers=self.headers, allow_redirects=True, **kwargs)
TypeError: get() got multiple values for keyword argument 'headers'
```

En effet le parser définit un "header", il faut que je vois comment le passer avec l'API_KEY désormais dans le nouveau paramètre des parsers : 

```py
######### Import Reservation ################

class ItineranceParser(Parser):
    label = u"Itinerance OpenSystem"
    url = 'https://e-iti-cms.open-system.fr/v2/2.9.6/routes'
    api_key = 'XXXXXXXXXXX'
    model = Trek
    eid = 'id'
    update_only = True
    delete = False
    fields = {
        'id': 'id',
        'reservation_id': 'id',
    }
    constant_fields = {
        'reservation_system': "Itinérance",
    }
    natural_keys = {
        'reservation_system': 'name',
    }

    @property
    def items(self):
        return self.root['data']

    def next_row(self):
        response = self.request_or_retry(self.url, headers={'Authorization': self.api_key})
        self.root = response.json()
        self.nb = int(self.root['nb'])
        for row in self.items:
            yield row

    def normalize_field_name(self, name):
        return name

    def filter_id(self, src, val):
        match = re.search(r'ITI-\d+-GEOT-(\d+)', val)
        if not match:
            raise RowImportError("Wrong if format {}".format(val))
        return match.group(1)

    def end(self):
        """Disable reservation for treks no not more in list"""
        treks = Trek.objects.filter(pk__in=self.to_delete)
        treks = treks.exclude(reservation_system=None, reservation_id='')
        treks.update(reservation_system=None, reservation_id='')
```

**Comment by Chatewgne** [comment]
Salut,
essaye de rajouter le header dans les variables de classe et pas dans l'appel à  `request_or_retry`:

> ```python
> 
> class ItineranceParser(Parser):
>     label = u"Itinerance OpenSystem"
>     url = 'https://e-iti-cms.open-system.fr/v2/2.9.6/routes'
>     api_key = 'XXXXXXXXXXX'
>     model = Trek
>     eid = 'id'
>     update_only = True
>     delete = False
>     headers= {'Authorization': 'XXXXXXX'}
>     fields = {
>         'id': 'id',
>         'reservation_id': 'id',
>     }
>     constant_fields = {
>         'reservation_system': "Itinérance",
>     }
>     natural_keys = {
>         'reservation_system': 'name',
>     }
> ```

**Comment by camillemonchicourt** [comment]
Ouais OK, merci sur ces précisions qui m'aident à voir comment renseigner le nouveau paramètre ``headers``.
Je vais creuser ça.

**Comment by camillemonchicourt** [comment]
OK ça fonctionner, merci.
