### ISSUE TITLE
Trek association to new typology entry causes an error

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4088]
Sur une instance de GTR3 accéder à la page d'un itinéraire associé à une nouvelle entrée de typologie provoque une erreur. Dans mon cas un nouveau type de réseau de randonnée, mais le problème est sans doute présent pour toutes les typologies.

- L'erreur ne dépend pas des statuts de publication.
- Typologie nouvellement créée ou associée pour la 1ère fois sans redémarrer l'instance

**Page erreur sur portail Geotrek rando**

> Sorry, this is not working properly.
> 
> We know about this issue and are working to fix it.
> 
> In the meantime, here is what you can do:
> 
>   - Refresh the page (sometimes it helps).
>   - Try again in 30 minutes.

**Erreur dans les logs**

```
TypeError: Cannot read properties of undefined (reading 'pictogramUri')
    at /app/src/.next/server/chunks/306.js:5779:50
    at Array.map (<anonymous>)
    at DetailsPreview (/app/src/.next/server/chunks/306.js:5774:90)
    at Wc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
    at Z (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
```

**Comment reproduire**

Côté Geotrek-admin :

- créer un nouveau type de réseau d'itinéraires avec un pictogramme
- y associer un itinéraire publié

Sur le portail rando :

- visiter la page de l'itinéraire

**Résolution**

Redémarrer l'instance GTR3 :

```bash
docker-compose restart nodeserver
```

**Tickets liés**

- https://github.com/GeotrekCE/Geotrek-rando-v3/issues/718
- https://github.com/GeotrekCE/Geotrek-admin/issues/3508

**Piste de solution**

GTR3 pourrait essayer de trouver la valeur en rafraîchissant son cache des typologies avant de laisser l'erreur se propager.

**Comment by marcantoinedupre** [comment]
Mauvais dépôt, le bug concerne geotrek-rando-v3. Transféré : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1123
