### ISSUE TITLE
Flaky test: `test_import_from_web_bad_parser`

### ISSUE THREAD

**Issue by marcantoinedupre** [GeotrekCE/Geotrek-admin#4103]
Ce test n'est pas déterministe. Il peut échouer alors sur la CI alors qu'il n'y a pas de changement lié.

Constaté le 06/05/2024 en version `2.105.0`.

**stacktrace**

```
======================================================================
FAIL: test_import_from_web_bad_parser (geotrek.common.tests.test_views.ViewsImportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/__w/Geotrek-admin/Geotrek-admin/geotrek/common/tests/test_views.py", line 269, in test_import_from_web_bad_parser
    self.assertContains(response_real, "Select a valid choice. 99 is not one of the available choices.")
  File "/__w/Geotrek-admin/Geotrek-admin/venv/lib/python3.8/site-packages/django/test/testcases.py", line 471, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
  File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : Couldn't find 'Select a valid choice. 99 is not one of the available choices.' in response

----------------------------------------------------------------------
```

**Comment by submarcos** [comment]
I suspect random translation bug. In fact, this should be a fomr test (value is not a valid choice), si move this test in a dedicated form test should be fine to validate it
