### ISSUE TITLE
Erreurs 502 API (DataTables warning: table id=objects-list)

### ISSUE THREAD

**Issue by eprouteau** [GeotrekCE/Geotrek-admin#4357]
Bonjour,

Je me permets de refaire un ticket car ne concerne pas l'API en docker.

J'ai donc le soucis "DataTables warning: table id=objects-list" 
![image](https://github.com/user-attachments/assets/fc20f506-a1f8-42a6-bc8c-85de82b73b40)

de même le front ne fonctionne plus.

Dans les deux cas, l'API renvoi des 502 [Lien exemple ](https://geotrekadmin.viree-outdoor.com/api/infrastructure/drf/infrastructures.datatables?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=type&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=false&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=conditions&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=false&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=cities&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=false&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=7&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1730895694965)

j'ai effectué toutes les manips suivantes :

- sudo systemctl restart geotrek
- Reboot nginx
- Reboot Postgres
- reboot geotrek > sudo systemctl restart geotrek
- Supprimé les dernier enregistrement en base (j'ajoute mes trek via qgis)
- MAJ de l'admin 107.1 > dernière version

Dans les Logs nginx et geotrek, rien de parlant mise a part les 502

Je vois aussi cette erreur : 

```
ERROR 2024-11-02 19:43:48,479 django.security.DisallowedHost Invalid HTTP_HOST header: '[146.59.197.220](https://146.59.197.220/)'. You may need to add '[146.59.197.220](https://146.59.197.220/)' to ALLOWED_HOSTS. 
Traceback (most recent call last): 
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/core/handlers/[exception.py](https://exception.py/)", line 55, in inner 
    response = get_response(request) 
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/utils/[deprecation.py](https://deprecation.py/)", line 133, in call 
    response = self.process_request(request) 
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/middleware/[common.py](https://common.py/)", line 48, in process_request 
    host = request.get_host() 
  File "/opt/geotrek-admin/lib/python3.8/site-packages/django/http/[request.py](https://request.py/)", line 150, in get_host 
    raise DisallowedHost(msg) 
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '[146.59.197.220](https://146.59.197.220/)'. You may need to add '[146.59.197.220](https://146.59.197.220/)' to ALLOWED_HOSTS.
```

J'arrive au bouts de mes investigation, donc je voulais savoir si vous auriez d'autres idées. Sachant que c'est arrivé d'un coup car aucunes modifs côté serveur (vps).

Bonne journée,

**Comment by camillemonchicourt** [comment]
Même sujet que https://github.com/GeotrekCE/Geotrek-admin/issues/4355 il me semble.

**Comment by eprouteau** [comment]
Oui je faisais un nouveau ticket car pas sur docker donc le problème pouvait être différent.

**Comment by submarcos** [comment]
Bonjour,
comme expliqué sur l'autre ticket il ne s'agit pas d'un seul problème, chaque cas est potentiellement différent.

De ce que je vois vous avec une erreur 502, ce qui est une erreur de communication entre nginx et gunicorn. 

Vous expliquez ajouter des treks via qgis, mais vous fournissez l'url de infrastructure.

Le module infrastructure n'est disponible qu'en mode "segmentation dynamique", qui lui même est incompatible avec le l'insertion de treks via QGis.

Peut etre une piste pour votre problème
